# Load all the configuration from custom zsh folder
for file in $(ls ~/.zsh/*.zsh);
do
  source $file
done

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH=bin:script:~/.bin:$PATH

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
