# Load all the configuration from custom zsh folder
for file in $(ls ~/.zsh/*.zsh);
do
  source $file
done

[ -z $TMUX ] || export TERM=screen-256color

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH=bin:script:~/.bin:$PATH

precmd() {
  if [[ -n "$TMUX" ]]; then
    tmux setenv "$(tmux display -p 'TMUX_PWD_#D')" "$PWD"
  fi
}

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
